version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec

formatters:
  enable:
    - gofumpt
    - goimports

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - gosec
